config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'reservations/new'
  get 'reservations/index'
  get 'reservations/show'
  post 'reservations/confirm'
  get 'reservations/create'
  post 'reservations/back'
  post 'reservations/complete'

  get 'users/new'
  get 'users/modify'
  post 'users/profile'
  get 'rooms/index'
  get 'rooms/search'

  post 'reserve/confirm' # 確認画面

  # devise_for :users

  resources :rooms
  resources :reservations
  Rails.application.routes.draw do
  get 'pages/home'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
  resources :users

  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
  has_one_attached :image

  def display_image
    image.variant(resize_to_limit: [100, 100])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # アカウント登録後のリダイレクト先
  def after_sign_up_path_for(_resource)
    users_modify_path
  end

  # アカウント編集後のリダイレクト先
  def after_update_path_for(_resource)
    user_path(current_user.id)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(_resource)
    # リダイレクト先のパス
    pages_home_path
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(_resource)
    # リダイレクト先のパス
    pages_home_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end

  def modify
    @user = User.find(current_user.id)
  end

  def profile
    @user = User.find(current_user.id)
    @user.image.attach(params[:user][:image])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
  <h1>ユーザー一覧</h1>
  <p class="subtitle">-- Users#index --</p>

  <% @users.each do |user| %>
    <hr width="40%">
    <%= image_tag user.display_image if user.image.attached? %>
    <p><span></span><%=link_to user.name, user_path(user.id) %></p>
    <p><span>自己紹介: </span><%=link_to user.introduction, user_path(user.id) %></p>
  <% end %>

app/views/users/modify.html.erb
<h1>アカウント設定</h1>
<p class="subtitle">-- Account Setting --</p>

<%= form_for @user, method: :post, url: users_profile_path do |f| %>

  <span class="image">
    <%= f.label :プロフィール画像 %><br />
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",style: "margin: 0 auto;"  %>
  </span>

  <div class="field">
    <%= f.label :名前 %><br />
    <%= f.text_field :name ,value:@user.name %>
  </div>

  <div class="field">
    <%= f.label :自己紹介 %><br />
    <%= f.text_field :introduction %>
  </div>

  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>登録済みの部屋</h1>
<p class="subtitle">-- My Rooms --</p>

<div class="container">
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col">
        <div style="display:flex;">
          <div>
            <% if room.image.attached? %>
              <%= image_tag room.customize_image(150,150) %>
            <% else %>
              <%= image_tag 'default_room.jpeg',:size => '150x150' %>
            <% end %>
          </div>

          <div>
            <p><%=link_to room.name, room_path(room.id) %></p>
            <p><span>場所:</span><%= room.address %></p>
            <p><span>オーナー: </span><%=link_to room.user.name, user_path(room.user.id) %></p>
            <p><span>内容: </span><%=link_to room.content, room_path(room.id) %></p>
            <p><span>¥</span><%= room.price %></p>
          </div>
          </div>
        </div>
    <% end %>
  </div>
</div>