config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'reservations/new'
  get 'reservations/index'
  get 'reservations/show'
  post 'reservations/confirm'
  get 'reservations/create'
  post 'reservations/back'
  post 'reservations/complete'

  get 'users/new'
  get 'users/modify'
  post 'users/profile'
  get 'rooms/index'
  get 'rooms/search'

  post 'reserve/confirm' # 確認画面

  # devise_for :users

  resources :rooms
  resources :reservations
  Rails.application.routes.draw do
  get 'pages/home'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
  resources :users

  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li style="list-style:none;"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= message %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="text-center">
    <p class="partial">©&nbsp;<%= Date.current.strftime('%Y') %>&nbsp;POTEPAN.INC.</h1>
  </p>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="nav-items px-3 nav">
    <div class="nav-items">
      <%= link_to "POTESHARE", pages_home_path,{class: "nav-item"} %>
      <% if user_signed_in? %>
        <%= form_with url: rooms_search_path,method: :get, local: true do |f| %>
            <%= f.text_field :search_area,{class: "search-box",:placeholder => "Search Area" } %>
            <%= f.text_field :search_keyword,{class: "search-box",:placeholder => "Search Keyword"} %>
          <%= f.submit "",class: "d-none submit-d-none" %>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if user_signed_in? %>  <!-- deviseのメソッドで、「ログインしているかしていないかでtrue or falseを返す」メソッド -->
        <%= link_to "新規投稿", new_room_path,{class: "nav-item"} %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-item" %>
        <%= link_to "登録済みの部屋", user_path(current_user.id),{class: "nav-item"} %>
        <%= link_to "予約履歴", reservations_path,{class: "nav-item"} %>
        <%= link_to "部屋一覧", rooms_path,{class: "nav-item"} %>
        <%= link_to "ユーザー一覧", users_path,{class: "nav-item"} %>
        <%= link_to "アカウント設定", users_modify_path,{class: "nav-item"} %>
      <% else %>
        <%= link_to("新規登録", new_user_registration_path,{class: "nav-item"}) %>
        <%= link_to "ログイン", new_user_session_path,{class: "nav-item"} %>
      <% end %>
    </div>
  </nav>
</header>