config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'reservations/new'
  get 'reservations/index'
  get 'reservations/show'
  post 'reservations/confirm'
  get 'reservations/create'
  post 'reservations/back'
  post 'reservations/complete'

  get 'users/new'
  get 'users/modify'
  post 'users/profile'
  get 'rooms/index'
  get 'rooms/search'

  post 'reserve/confirm' # 確認画面

  # devise_for :users

  resources :rooms
  resources :reservations
  Rails.application.routes.draw do
  get 'pages/home'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
  resources :users

  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
  end

  def index
    @reservations = Reservation.paginate(page: params[:page], per_page: 5)
  end

  def back
    @reservation = Reservation.new(reservation_params)
    redirect_to room_path(@reservation.room_id)
  end

  def complete
    Reservation.create(reservation_params)
    render('reservations/complete')
  end

  def show
    @reservation = Reservation.find(params[:room_id])
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(@reservation.room_id)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    # @room = Room.find(params[:id])
    # フォームから送られてきたデータ(body)をストロングパラメータを経由して@roomに代入
    # @reservation.save

    redirect_to reservation_path(@reservation)
    # redirect_to action: 'confirm'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:room_id, :persons, :start_date, :end_date, :total_price) # roomモデルのカラムのみを許可
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/complete.html.erb
<h1>予約完了</h1>
<p>-- Completed Reservation --</p>

<p>予約が完了しました。</p>

<%= link_to "部屋一覧へ", rooms_path,{class: "nav-item"} %>

app/views/reservations/confirm.html.erb
<h1>予約確認</h1>
<p>-- Confirm Reservation --</p>
<h3>
	合計料金：
	<% @reservation.total_price = @room.price * @reservation.persons %>
	<%= @reservation.total_price %><br>
</h3>
<h3>
	予約人数：
	<%= @reservation.persons %><br>
</h3>
<h3>
	部屋番号：
	<%= @reservation.room_id %><br>
</h3>
<h3>
	開始日：
	<%= @reservation.start_date %><br>
</h3>
<h3>
	終了日：
	<%= @reservation.end_date %><br>
</h3>

<%= form_for @reservation, method: :post, url: reservations_complete_path do |form| %>
	<%= form.hidden_field :total_price %>
	<%= form.hidden_field :persons %>
	<%= form.hidden_field :room_id %>
	<%= form.hidden_field :start_date %>
	<%= form.hidden_field :end_date %>
	<%= form.submit '送信する' %>
<% end %>

<%= form_for @reservation, method: :post, url: reservations_back_path do |form| %>
	<%= form.hidden_field :total_price %>
	<%= form.hidden_field :persons %>
  <%= form.hidden_field :room_id %>
	<%= form.submit '入力画面に戻る' %>
<% end %>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/index.html.erb
<h1>予約一覧</h1>
<p class="subtitle">-- Reservations --</p>

    <% @reservations.each do |reservation| %>
          <div> 
            <p><%=link_to "予約ID：#{reservation.id}", reservation_path(reservation.id) %></p>
            <div>
              <p><span>予約人数:</span><%= reservation.persons %></p>
              <p><span>合計料金:¥</span><%= reservation.total_price %></p>
            </div>
            <div>
              <p><span>開始日:</span><%= reservation.start_date %></p>
              <p><span>終了日:</span><%= reservation.end_date %></p>
              <p><span>予約完了日:</span><%= reservation.created_at.strftime("%Y年%m月%d日") %></p>
            </div>
          </div>
          <hr>
    <% end %>
    <%= will_paginate @books, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

<%= bootstrap_form_for @reservation , method: :post, url: reservations_confirm_path do |f|%>
  <p>
      <%= f.label :persons,"" %>
      <%= f.number_field :persons %>
    </p>
  <p>
    <%= f.label :total_price,"" %>
    <%= f.number_field :total_price %>
  </p>
  <p>
    <%= f.label :room_id,"" %>
    <%= f.number_field :room_id %>
  </p>
  <%= f.submit %>
<% end %>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<p><span>合計料金: </span><%= @reservation.total_price %></p> 
<p><span>人数: </span><%= @reservation.persons %></p>
<p><span>予約確定日: </span><%= @reservation.created_at %></p>