config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'reservations/new'
  get 'reservations/index'
  get 'reservations/show'
  post 'reservations/confirm'
  get 'reservations/create'
  post 'reservations/back'
  post 'reservations/complete'

  get 'users/new'
  get 'users/modify'
  post 'users/profile'
  get 'rooms/index'
  get 'rooms/search'

  post 'reserve/confirm' # 確認画面

  # devise_for :users

  resources :rooms
  resources :reservations
  Rails.application.routes.draw do
  get 'pages/home'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
  resources :users

  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 200 }
  validates :image, presence: true
  validates :price, presence: true
  validates :address, presence: true

  def self.search(search_area, search_keyword)
    if search_area != '' && search_keyword != ''
      Room.where(['address LIKE ? AND content LIKE ?', "%#{search_area}%", "%#{search_keyword}%"])
    elsif search_area != '' && search_keyword == ''
      Room.where(['address LIKE ?', "%#{search_area}%"])
    elsif search_area == '' && search_keyword != ''
      Room.where(['content LIKE ?', "%#{search_keyword}%"])
    else
      Room.all
    end
  end

  def display_image
    image.variant(resize_to_limit: [100, 100])
  end

  def ditail_image
    image.variant(resize_to_limit: [500, 500])
  end

  def customize_image(height, width)
    image.variant(resize_to_limit: [height, width])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]  # deviseのメソッドで「ログインしていないユーザーをログイン画面に送る」メソッド

  def index
    @rooms = Room.paginate(page: params[:page], per_page: 12)
  end

  def new
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
    @user = @room.user
    @reservation = Reservation.new
  end

  def edit; end

  def create
    @room = Room.new(room_params)
    @room.image.attach(params[:room][:image])
    @room.user_id = current_user.id
    if @room.save
      redirect_to rooms_path
    else
      flash.now[:danger] = '登録に失敗しました。'
      render 'rooms/new'
    end
  end

  def search
    @rooms = Room.search(params[:search_area], params[:search_keyword]).order(id: 'DESC')
    @count = @rooms.count
    @room = Room.new
  end

  def update; end

  def destroy; end

  private

  def room_params
    params.require(:room).permit(:name, :content, :address, :price, :image) # roomモデルのカラムのみを許可
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h1>部屋一覧</h1>
<p class="subtitle">-- Rental Rooms --</p>

<div class="container">
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col">
        <div style="display:flex;">
          <div>
            <% if room.image.attached? %>
              <%= image_tag room.customize_image(150,150) %>
            <% else %>
              <%= image_tag 'default_room.jpeg',:size => '150x150' %>
            <% end %>
          </div>

          <div>
            <p><%=link_to room.name, room_path(room.id) %></p>
            <p><span>場所:</span><%= room.address %></p>
            <p><span>オーナー: </span><%=link_to room.user.name, user_path(room.user.id) %></p>
            <p><span>内容: </span><%=link_to room.content, room_path(room.id) %></p>
            <p><span>¥</span><%= room.price %></p>
          </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<%= will_paginate @books, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/rooms/new.html.erb
<h1>ルーム新規投稿</h1>
<p class="subtitle">-- Post Room --</p>

<%= render 'shared/error_messages', model: @room %>

<%= form_for @room do |f| %>
  <p>
      <%= f.label :name,"ルーム名(Name)" %><span style="color:red;">*</span>
      <%= f.text_field :name %>
    </p>
  <p>
    <%= f.label :content,"ルーム紹介(Content)" %><span style="color:red;">*</span>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :address,"住所(Address)" %><span style="color:red;">*</span>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :price,"料金(Price)" %><span style="color:red;">*</span>
    <%= f.number_field :price %>
  </p>
    <%= f.label :price,"ルーム画像(Image)" %><span style="color:red;">*</span>
    <%= f.file_field :image , accept: "image/jpeg,image/gif,image/png",class: "",style: "margin: 0 auto;"  %>
  <%= f.submit %>
<% end %>

app/views/rooms/search.html.erb
<h1>検索結果</h1>
<p class="subtitle">-- Search Result --</p>

<h4>該当件数：<%= @count %>&nbsp;件</h4>
<% if @count == 0 %>
  <p>該当する部屋は見つかりませんでした。</p>
<% else %>
<div class="container">
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col">
        <div style="display:flex;">
          <div>
            <% if room.image.attached? %>
              <%= image_tag room.customize_image(150,150) %>
            <% else %>
              <%= image_tag 'default_room.jpeg',:size => '150x150' %>
            <% end %>
          </div>

          <div>
            <p><%=link_to room.name, room_path(room.id) %></p>
            <p><span>場所:</span><%= room.address %></p>
            <p><span>オーナー: </span><%=link_to room.user.name, user_path(room.user.id) %></p>
            <p><span>内容: </span><%=link_to room.content, room_path(room.id) %></p>
            <p><span>¥</span><%= room.price %></p>
          </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/rooms/show.html.erb
<h1>部屋詳細</h1>
<p class="subtitle">-- Room Detail --</p>
<div class="container d-inline-flex">
  <div>
    <% if @room.image.attached? %>
      <%= image_tag @room.customize_image(600,500) %>
    <% else %>
      <%= image_tag 'default_room.jpeg',:size => '600x500' %>
    <% end %>
  </div>
  <% if current_user.id != @room.user_id %>
  <div style="margin: 0 auto; margin-top:18px;" >
  <% else %>
  <div style="margin: 0 auto; margin-top:140px;" >
  <% end %>
    <h2><%= @room.name %></h2>
    <p><span>オーナー: </span><%= @user.name %></p>
    <p><span>内容: </span><%= @room.content %></p>
    <p><span>料金: </span><%= @room.price %></p>
    <hr style="color:black;">
  <% if current_user.id != @room.user_id %>
    <%= form_for @reservation , method: :post, url: reservations_confirm_path do |f|%> 
      <p>
          <%= f.label :persons,"人数" %>
          <%= f.number_field :persons %>
        </p>
        <p>
          <%= f.label :start_date,"宿泊開始日" %>
          <%= f.date_field :start_date %>
        </p>
        <p>
          <%= f.label :end_date,"宿泊終了日" %>
          <%= f.date_field :end_date %>
        </p>
        <%= f.hidden_field :room_id,:value => @room.id %>
      <%= f.submit "予約する" %>
    <% end %>
  <% end %>
  </div>
</div>